# Generated by Django 5.1.7 on 2025-03-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='detailed_description',
        ),
        migrations.AddField(
            model_name='blog',
            name='short_content',
            field=models.TextField(default='No short content available'),
        ),
        migrations.AddField(
            model_name='blog',
            name='user_name',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
