# Generated by Django 5.1.7 on 2025-03-31 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_content_blog_detailed_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='detailed_description',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='short_content',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='user_name',
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
