# Generated by Django 5.1.7 on 2025-03-31 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_detailed_description_blog_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='short_description',
            field=models.CharField(default='No description available.', max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='username',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
    ]
