# Generated by Django 5.1.7 on 2025-03-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_short_description_blog_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='country',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
